In [1]:
import numpy as np

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [17]:
def moving_avg(a, k):
    mv_avg =  np.array([])
    i = 0
    for j in a:
        if i <= (len(a)-k):
            x = (a[i]+a[i+1]+a[i+2])/3
            mv_avg = np.append(mv_avg, x)
            i=i+1
        else :
            break
    return mv_avg

result = moving_avg(a, 3)
result

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

Write a function so that the columns of the output matrix are powers of the input
vector.

In [26]:
x = np.array([2,3,4,5])
N = 5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
matrix

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [24]:
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

In [25]:
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_dec_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [27]:
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)
op_matx_inc_order 

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])